/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui.User;

import model.UserDetails;
import com.db4o.*;
import com.db4o.ext.DatabaseClosedException;
import com.db4o.ext.Db4oIOException;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.Arrays;
import java.util.HashMap;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import model.AdminDetails;
import ui.Admin.AdminSystem;

/**
 *
 * @author shubhampatil
 */
public class UserSystem extends javax.swing.JFrame {

    /**
     * Creates new form UserSystem
     */
    public UserSystem() {
        initComponents();
        PopulateHashMap();
        setAdminElementsVisibility(false);
    }
    HashMap<String, UserDetails> UserMap = new HashMap<>();
    HashMap<String, AdminDetails> AdminMap = new HashMap<>();
    
    void setAdminElementsVisibility(boolean visibility){
        lblEnterprise.setVisible(visibility);
        cmbBoxEnterprise.setVisible(visibility);
        lblOrg.setVisible(visibility);
        cmbBoxOrg.setVisible(visibility);
    }
    
    void clearallfields(){
        txtUserEmail.setText("");
        txtPassword.setText("");
        buttonGroup1.clearSelection();
        setAdminElementsVisibility(false);
    }
    
    
    void PopulateHashMap(){
        HashMap<String, UserDetails> UserMap = new HashMap<>();
        HashMap<String, AdminDetails> AdminMap = new HashMap<>();
        
        Path currentRelativePath = Paths.get("");
        String s = currentRelativePath.toAbsolutePath().toString();
        String UserFILEPath = s + "/Databases/Users.db";
        String AdminFILEPath = s + "/Databases/Admins.db";
        
        ObjectContainer Userdb = Db4oEmbedded.openFile(Db4oEmbedded.newConfiguration(), UserFILEPath);
        ObjectContainer Admindb = Db4oEmbedded.openFile(Db4oEmbedded.newConfiguration(), AdminFILEPath);
        
        UserDetails u;
        AdminDetails a;
        try {
            List<UserDetails> userresult = Userdb.query(UserDetails.class);
            List<AdminDetails> adminresult = Userdb.query(AdminDetails.class);
            if(userresult.isEmpty() && adminresult.isEmpty())
                return;

            Iterator useritr = userresult.iterator();
            while(useritr.hasNext()){
                u = (UserDetails)useritr.next();
                UserMap.put(u.getEmail(), u);
            }
            
            Iterator adminitr = adminresult.iterator();
            while(adminitr.hasNext()){
                a = (AdminDetails)adminitr.next();
                AdminMap.put(a.getEmail(), a);
            }
        }
        catch(DatabaseClosedException | Db4oIOException E){
            JOptionPane.showMessageDialog(this, "Database Error.");
        }
        finally{
            Userdb.close();
            Admindb.close();
        }
        this.UserMap = UserMap;
        this.AdminMap = AdminMap;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        buttonGroup1 = new javax.swing.ButtonGroup();
        SplitPane = new javax.swing.JSplitPane();
        LogInPanel = new javax.swing.JPanel();
        lblVirtualCare = new javax.swing.JLabel();
        lblSignIn = new javax.swing.JLabel();
        lblUserEmail = new javax.swing.JLabel();
        txtUserEmail = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSignIn = new javax.swing.JButton();
        cmbBoxEnterprise = new javax.swing.JComboBox<>();
        rdBtnUser = new javax.swing.JRadioButton();
        rdBtnAdmin = new javax.swing.JRadioButton();
        hiddenPanel = new javax.swing.JPanel();
        cmbBoxOrg = new javax.swing.JComboBox<>();
        lblOrg = new javax.swing.JLabel();
        lblEnterprise = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        btnSignUp = new javax.swing.JButton();
        btnLogIn = new javax.swing.JButton();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblVirtualCare.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        lblVirtualCare.setText("VIRTUAL CARE");

        lblSignIn.setText("Sign In");

        lblUserEmail.setText("User Email :");

        jLabel1.setText("Password:");

        btnSignIn.setText("Sign In");
        btnSignIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignInActionPerformed(evt);
            }
        });

        cmbBoxEnterprise.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbBoxEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBoxEnterpriseActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdBtnUser);
        rdBtnUser.setText("User");
        rdBtnUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnUserActionPerformed(evt);
            }
        });

        buttonGroup1.add(rdBtnAdmin);
        rdBtnAdmin.setText("Admin");
        rdBtnAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdBtnAdminActionPerformed(evt);
            }
        });

        lblOrg.setText("Organisation");

        javax.swing.GroupLayout hiddenPanelLayout = new javax.swing.GroupLayout(hiddenPanel);
        hiddenPanel.setLayout(hiddenPanelLayout);
        hiddenPanelLayout.setHorizontalGroup(
            hiddenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hiddenPanelLayout.createSequentialGroup()
                .addGroup(hiddenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(hiddenPanelLayout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(cmbBoxOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(hiddenPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblOrg)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        hiddenPanelLayout.setVerticalGroup(
            hiddenPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hiddenPanelLayout.createSequentialGroup()
                .addContainerGap(23, Short.MAX_VALUE)
                .addComponent(lblOrg)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmbBoxOrg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        lblEnterprise.setText("Enterprise:");

        javax.swing.GroupLayout LogInPanelLayout = new javax.swing.GroupLayout(LogInPanel);
        LogInPanel.setLayout(LogInPanelLayout);
        LogInPanelLayout.setHorizontalGroup(
            LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPanelLayout.createSequentialGroup()
                .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInPanelLayout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addComponent(lblUserEmail))
                        .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(LogInPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(LogInPanelLayout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addComponent(lblVirtualCare, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LogInPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(LogInPanelLayout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(rdBtnUser)
                        .addGap(18, 18, 18)
                        .addComponent(rdBtnAdmin))
                    .addGroup(LogInPanelLayout.createSequentialGroup()
                        .addGap(291, 291, 291)
                        .addComponent(lblSignIn)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBoxEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(132, 132, 132))
            .addGroup(LogInPanelLayout.createSequentialGroup()
                .addGap(278, 278, 278)
                .addComponent(btnSignIn)
                .addGap(90, 90, 90)
                .addComponent(hiddenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogInPanelLayout.setVerticalGroup(
            LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogInPanelLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(lblVirtualCare, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblSignIn)
                .addGap(25, 25, 25)
                .addComponent(lblEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LogInPanelLayout.createSequentialGroup()
                        .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblUserEmail)
                            .addComponent(txtUserEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(50, 50, 50)
                        .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(LogInPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(rdBtnUser)
                            .addComponent(rdBtnAdmin))
                        .addGap(48, 48, 48)
                        .addComponent(btnSignIn))
                    .addGroup(LogInPanelLayout.createSequentialGroup()
                        .addComponent(cmbBoxEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(hiddenPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(365, Short.MAX_VALUE))
        );

        SplitPane.setRightComponent(LogInPanel);

        btnSignUp.setText("Sign Up");
        btnSignUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSignUpActionPerformed(evt);
            }
        });

        btnLogIn.setText("Log In");
        btnLogIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogInActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSignUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnLogIn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addComponent(btnSignUp)
                .addGap(34, 34, 34)
                .addComponent(btnLogIn)
                .addContainerGap(385, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(SplitPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbBoxEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBoxEnterpriseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBoxEnterpriseActionPerformed

    private void btnSignUpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignUpActionPerformed
        // TODO add your handling code here:
        SignUp SignUppanel = new SignUp();
        SplitPane.setRightComponent(SignUppanel);
    }//GEN-LAST:event_btnSignUpActionPerformed

    private void rdBtnUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnUserActionPerformed
        // TODO add your handling code here:
        setAdminElementsVisibility(false);
    }//GEN-LAST:event_rdBtnUserActionPerformed

    private void btnSignInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSignInActionPerformed
        // TODO add your handling code here:
        UserDetails u = UserMap.get(txtUserEmail.getText().trim());
        AdminDetails a = AdminMap.get(txtUserEmail.getText().trim());
        if(txtUserEmail.getText().trim().equals("SysAdmin@virtualcare.com") && String.valueOf(txtPassword.getPassword()).equals("SysAdmin") && rdBtnAdmin.isSelected()){
            AdminSystem Dashboard = new AdminSystem(a);
            SplitPane.setRightComponent(Dashboard);
        }
        else if((rdBtnUser.isSelected() && u == null) || (rdBtnAdmin.isSelected() && a == null)){
            JOptionPane.showMessageDialog(this, "Email Doesn't Exist. Please Signup.");
        }
        else if(rdBtnAdmin.isSelected()){
                if(!Arrays.toString(txtPassword.getPassword()).equals(a.getPassword()) || !a.getEnterprise().equalsIgnoreCase(cmbBoxEnterprise.getSelectedItem().toString()))
                    JOptionPane.showMessageDialog(this, "Incorrect Password. Try Again.");
                else if(!a.getOrganization().equalsIgnoreCase(cmbBoxOrg.getSelectedItem().toString())){
                    JOptionPane.showMessageDialog(this, "Choose Correct Organization. Try Again.");
                }
        }
        else if (rdBtnUser.isSelected()){
            if(!Arrays.toString(txtPassword.getPassword()).equals(u.getPassword()))
                JOptionPane.showMessageDialog(this, "Incorrect Password. Try Again.");
            else{
                UserDashboard Dashboard = new UserDashboard(u);
                SplitPane.setRightComponent(Dashboard);
            }
        }
        else{
            JOptionPane.showMessageDialog(this, "Select type of user.");
        }
        clearallfields();
    }//GEN-LAST:event_btnSignInActionPerformed

    private void btnLogInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogInActionPerformed
        // TODO add your handling code here:
        SplitPane.setRightComponent(LogInPanel);
        PopulateHashMap();
    }//GEN-LAST:event_btnLogInActionPerformed

    private void rdBtnAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdBtnAdminActionPerformed
        // TODO add your handling code here:
        setAdminElementsVisibility(true);
    }//GEN-LAST:event_rdBtnAdminActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LogInPanel;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton btnLogIn;
    private javax.swing.JButton btnSignIn;
    private javax.swing.JButton btnSignUp;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cmbBoxEnterprise;
    private javax.swing.JComboBox<String> cmbBoxOrg;
    private javax.swing.JPanel hiddenPanel;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEnterprise;
    private javax.swing.JLabel lblOrg;
    private javax.swing.JLabel lblSignIn;
    private javax.swing.JLabel lblUserEmail;
    private javax.swing.JLabel lblVirtualCare;
    private javax.swing.JRadioButton rdBtnAdmin;
    private javax.swing.JRadioButton rdBtnUser;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserEmail;
    // End of variables declaration//GEN-END:variables
}
