/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui.NGO;

import com.db4o.ext.DatabaseClosedException;
import com.db4o.ext.Db4oIOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import javax.swing.table.DefaultTableModel;
import model.NGORequests;
import ui.User.UserDashboard;
import ui.User.UserSystem;

/**
 *
 * @author shubhampatil
 */
public class NgoCommittie extends javax.swing.JPanel {

    /**
     * Creates new form NgoCommittie
     */
    public NgoCommittie(JSplitPane SplitPane) {
        initComponents();
        DefaultTableModel NGOMod = (DefaultTableModel) NGORequestsTableNC.getModel();
        this.NGOMod = NGOMod;
        PullNGORequeststoList();
        populateNGOtable();
        this.SplitPane = SplitPane;
    }
    
    JSplitPane SplitPane;
    ArrayList<NGORequests> NGOReqs;
    DefaultTableModel NGOMod;
    NGORequests N;
    
    void PullNGORequeststoList(){
        ArrayList<NGORequests> NGOs = new ArrayList<>();

        NGORequests N;
        try {
            List<NGORequests> NGOresult = UserSystem.NGOdb.query(NGORequests.class);
            if(NGOresult.isEmpty())
                return;
            Iterator NGOitr = NGOresult.iterator();
            while(NGOitr.hasNext()){
                N = (NGORequests)NGOitr.next();
                    NGOs.add(N);
            }
        }
        catch(DatabaseClosedException | Db4oIOException E){
            JOptionPane.showMessageDialog(this, "Database Error.");
        }
        this.NGOReqs = NGOs;
    }
    
    void populateNGOtable(){
        NGOMod.setRowCount(0);
        try{
            Iterator itr = NGOReqs.iterator();
            while(itr.hasNext()){
                NGORequests N = (NGORequests)itr.next();
                if(N.getStatus().equalsIgnoreCase("Committee Review")){
                    String data[] = {N.getPatientID(), String.valueOf(N.getAnnualIncome()), String.valueOf(N.getAmount()), N.getToNGOOrg(), N.getStatus()};
                    NGOMod.addRow(data);
                }
            }
        }
        catch(NullPointerException E){
            JOptionPane.showMessageDialog(this, "No Active NGO Requests available");
        }
    }
    
    void ShowExplaination(NGORequests N){
        jLabel1.setText(N.getExplaination());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        NGORequestsTableNC = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnApproveNC = new javax.swing.JButton();
        btnDeclineNC = new javax.swing.JButton();
        btnLogoutNC = new javax.swing.JButton();
        btnView = new javax.swing.JButton();

        NGORequestsTableNC.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "PatientID", "Annual Income", "Amount", "Organisation", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(NGORequestsTableNC);

        jLabel2.setText("Explanation:");

        btnApproveNC.setText("Approve");
        btnApproveNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnApproveNCActionPerformed(evt);
            }
        });

        btnDeclineNC.setText("Decline");
        btnDeclineNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclineNCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(90, 90, 90))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(btnApproveNC)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDeclineNC)
                .addGap(141, 141, 141))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnApproveNC)
                    .addComponent(btnDeclineNC))
                .addContainerGap())
        );

        btnLogoutNC.setText("Logout");
        btnLogoutNC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutNCActionPerformed(evt);
            }
        });

        btnView.setText("View");
        btnView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnLogoutNC)
                        .addGap(67, 67, 67)
                        .addComponent(btnView))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogoutNC)
                    .addComponent(btnView))
                .addGap(6, 6, 6)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutNCActionPerformed
        // TODO add your handling code here:
        UserSystem LoginPanel = new UserSystem();
        SplitPane.removeAll();
        SplitPane.add(LoginPanel.SplitPane);
        SplitPane.repaint();
    }//GEN-LAST:event_btnLogoutNCActionPerformed

    private void btnDeclineNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclineNCActionPerformed
        // TODO add your handling code here:
        if(N == null){
            JOptionPane.showMessageDialog(this, "View a Patient first.");
        }
        else{
            N.setStatus("Declined");
            UserDashboard.AddNGOtoDB(N);
            JOptionPane.showMessageDialog(this, "Request Declined.");
            populateNGOtable();
        }
    }//GEN-LAST:event_btnDeclineNCActionPerformed

    private void btnViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewActionPerformed
        // TODO add your handling code here:
        if(NGORequestsTableNC.getSelectedRow() < 0)
            return;
        int Row = NGORequestsTableNC.getSelectedRow();
        String PatientID = NGORequestsTableNC.getValueAt(Row, 0).toString();
        int Amount = Integer.parseInt(NGORequestsTableNC.getValueAt(Row, 2).toString());
        String Organisation = NGORequestsTableNC.getValueAt(Row, 3).toString();
        
        NGORequests N;
        Iterator itr = NGOReqs.iterator();
        while(itr.hasNext()){
            N = (NGORequests)itr.next();
            if(N.getPatientID().equalsIgnoreCase(PatientID) && N.getAmount() == Amount && N.getToNGOOrg().equalsIgnoreCase(Organisation)){
                ShowExplaination(N);
                this.N = N;
            }
        }
    }//GEN-LAST:event_btnViewActionPerformed

    private void btnApproveNCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnApproveNCActionPerformed
        // TODO add your handling code here:
        if(N == null){
            JOptionPane.showMessageDialog(this, "View a Patient first.");
        }
        else{
            N.setStatus("Approved");
            UserDashboard.AddNGOtoDB(N);
            JOptionPane.showMessageDialog(this, "Request Approved.");
            populateNGOtable();
        }
    }//GEN-LAST:event_btnApproveNCActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable NGORequestsTableNC;
    private javax.swing.JButton btnApproveNC;
    private javax.swing.JButton btnDeclineNC;
    private javax.swing.JButton btnLogoutNC;
    private javax.swing.JButton btnView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
